"""empty message

Revision ID: 1bea0105e8a2
Revises: 641089a7755b
Create Date: 2023-06-03 15:25:57.988954

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1bea0105e8a2'
down_revision = '641089a7755b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('atama', schema=None) as batch_op:
        batch_op.add_column(sa.Column('atama_gun', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('atama', schema=None) as batch_op:
        batch_op.drop_column('atama_gun')

    # ### end Alembic commands ###
