"""empty message

Revision ID: 254d82b0a0b2
Revises: 
Create Date: 2023-05-18 16:09:25.179097

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '254d82b0a0b2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hat',
    sa.Column('hat_id', sa.Integer(), nullable=False),
    sa.Column('hat_ad', sa.String(length=150), nullable=True),
    sa.Column('hat_no', sa.String(length=150), nullable=True),
    sa.PrimaryKeyConstraint('hat_id')
    )
    op.create_table('otobus',
    sa.Column('otobus_id', sa.BigInteger(), nullable=False),
    sa.Column('otobus_tur', sa.String(length=150), nullable=True),
    sa.Column('otobus_sayı', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('otobus_id')
    )
    op.create_table('sofor',
    sa.Column('sofor_id', sa.BigInteger(), nullable=False),
    sa.Column('sofor_ad', sa.String(length=150), nullable=True),
    sa.Column('sofor_soyad', sa.String(length=150), nullable=True),
    sa.Column('cinsiyet', sa.String(length=150), nullable=True),
    sa.PrimaryKeyConstraint('sofor_id')
    )
    op.create_table('sefer',
    sa.Column('sefer_id', sa.Integer(), nullable=False),
    sa.Column('sefer_tarih', sa.String(length=150), nullable=True),
    sa.Column('sefer_saat', sa.String(length=150), nullable=True),
    sa.Column('hat_id', sa.Integer(), nullable=True),
    sa.Column('otobus_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['hat_id'], ['hat.hat_id'], ),
    sa.ForeignKeyConstraint(['otobus_id'], ['otobus.otobus_id'], ),
    sa.PrimaryKeyConstraint('sefer_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sefer')
    op.drop_table('sofor')
    op.drop_table('otobus')
    op.drop_table('hat')
    # ### end Alembic commands ###
