"""empty message

Revision ID: 641089a7755b
Revises: 8dff4b753b63
Create Date: 2023-05-30 13:12:14.728763

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '641089a7755b'
down_revision = '8dff4b753b63'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('atama',
    sa.Column('atama_id', sa.BigInteger(), nullable=False),
    sa.Column('atama_durum', sa.Boolean(), nullable=True),
    sa.Column('atama_saat', sa.String(length=150), nullable=True),
    sa.Column('atama_sonuc', sa.String(length=320000), nullable=True),
    sa.PrimaryKeyConstraint('atama_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('atama')
    # ### end Alembic commands ###
