"""empty message

Revision ID: 8dff4b753b63
Revises: a6a94a8d1041
Create Date: 2023-05-30 13:10:41.801096

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8dff4b753b63'
down_revision = 'a6a94a8d1041'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('otobus', schema=None) as batch_op:
        batch_op.add_column(sa.Column('otobus_kapasite', sa.BigInteger(), nullable=True))
        batch_op.drop_column('otobus_sayi')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('otobus', schema=None) as batch_op:
        batch_op.add_column(sa.Column('otobus_sayi', sa.BIGINT(), autoincrement=False, nullable=True))
        batch_op.drop_column('otobus_kapasite')

    # ### end Alembic commands ###
