"""empty message

Revision ID: 9ea2b011098e
Revises: 1bea0105e8a2
Create Date: 2023-06-04 11:07:49.756999

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ea2b011098e'
down_revision = '1bea0105e8a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('atama', schema=None) as batch_op:
        batch_op.add_column(sa.Column('atama_tarih', sa.String(length=150), nullable=True))
        batch_op.drop_column('atama_saat')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('atama', schema=None) as batch_op:
        batch_op.add_column(sa.Column('atama_saat', sa.VARCHAR(length=150), autoincrement=False, nullable=True))
        batch_op.drop_column('atama_tarih')

    # ### end Alembic commands ###
