"""empty message

Revision ID: a6a94a8d1041
Revises: 0301cd400cfe
Create Date: 2023-05-30 12:48:54.755663

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6a94a8d1041'
down_revision = '0301cd400cfe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sefer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sofor_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'sofor', ['sofor_id'], ['sofor_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sefer', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('sofor_id')

    # ### end Alembic commands ###
